#!/usr/bin/env ruby
require 'rubygems'
require 'open-uri'
require 'nokogiri'

require './fetch_txr'
require './fetch_deed'
# require './fetch_deed'

# Fetches Real Estate information from public tax records

tax = '5708080100000'
year = Date.today.year.to_s

text_divider = "-------"

# Prints a character to show it's doing something
def impatient()
  impatient = Thread.new do
    loop do
      print "."
      sleep 0.25
    end
  end.run
end

puts 'This is like, SO fetch!'
puts text_divider
print 'Getting the last deed number from tax records.'
impatient
txr_deed = fetch_txr(tax, year)
impatient.kill
puts text_divider
puts txr_deed

